TARGETS += $(BUILD_DIR)/wustdlib
WUSTDLIB_CFLAGS := -nostdlib -ffreestanding
LDFLAGS := -nostartfiles

$(BUILD_DIR)/wustdlib : $(BUILD_DIR)/wustdlib.o
	$(CC) $(LDFLAGS) -o $@ $^

$(BUILD_DIR)/wustdlib.o : $(SRC_DIR)/wustdlib/wustdlib.c | $(BUILD_DIR)
	$(CC) $(WUSTDLIB_CFLAGS) -c -o $@ $<
